%%%% Better Poster latex template example v1.0 (2019/04/04)
%%%% GNU General Public License v3.0
%%%% Rafael Bailo
%%%% https://github.com/rafaelbailo/betterposter-latex-template
%%%% 
%%%% Original design from Mike Morrison
%%%% https://twitter.com/mikemorrison

\documentclass[a0paper,fleqn]{betterposter}

%%%% Uncomment the following commands to customise the format

%% Setting the width of columns
% Left column
%\setlength{\leftbarwidth}{0.25\paperwidth}
% Right column
%\setlength{\rightbarwidth}{0.25\paperwidth}

%% Setting the column margins
% Horizontal margin
%\setlength{\columnmarginvertical}{0.05\paperheight}
% Vertical margin
%\setlength{\columnmarginhorizontal}{0.05\paperheight}
% Horizontal margin for the main column
%\setlength{\maincolumnmarginvertical}{0.15\paperheight}
% Vertical margin for the main column
%\setlength{\maincolumnmarginhorizontal}{0.15\paperheight}

%% Changing font sizes
% Text font
%\renewcommand{\fontsizestandard}{\fontsize{28}{35} \selectfont}
% Main column font
%\renewcommand{\fontsizemain}{\fontsize{28}{35} \selectfont}
% Title font
\renewcommand{\fontsizetitle}{\fontsize{28}{35} \selectfont}
% Author font
%\renewcommand{\fontsizeauthor}{\fontsize{28}{35} \selectfont}
% Section font
%\renewcommand{\fontsizesection}{\fontsize{28}{35} \selectfont}

%% Changing font sizes for a specific text segment
% Place the text inside brackets:
% {\fontsize{28}{35} \selectfont Your text goes here}

%% Changing colours
% Background of side columns
%\renewcommand{\columnbackgroundcolor}{black}
% Font of side columns
%\renewcommand{\columnfontcolor}{gray}
% Background of main column
%\renewcommand{\maincolumnbackgroundcolor}{empirical}
%\renewcommand{\maincolumnbackgroundcolor}{theory}
%\renewcommand{\maincolumnbackgroundcolor}{methods}
%\renewcommand{\maincolumnbackgroundcolor}{intervention}
% Font of main column
%\renewcommand{\maincolumnfontcolor}{gray}

\usepackage[
backend=biber,
style=alphabetic,
sorting=ynt
]{biblatex}
\addbibresource{my.bib}
\addbibresource{references.bib}

\begin{document}	
\betterposter{
%%%%%%%% MAIN COLUMN

\maincolumn{
%%%% Main space

\textbf{We failed to detect a causal effect of FMD on CKD}. However, due to the \textbf{small FMD GWAS sample size}, we had \textbf{limited power}. 
}{
%%%% Bottom space

%% QR code
\qrcode{qr}{img/smartphoneWhite}{
\textbf{Take a picture} to
\\visit the Github repository  
}
% Smartphone icon
% Author: Freepik
% Retrieved from: https://www.flaticon.com/free-icon/smartphone_65680

%% Compact QR code (comment the previous command and uncomment this one to switch)
%\compactqrcode{img/qrcode}{
%\textbf{Take a picture} to
%\\vissit the full paper
%}

}

}{
%%%%%%%% LEFT COLUMN

\title{Does Fibromuscular Dysplasia Cause Chronic Kidney Disease? A Two-Sample Mendelian Randomization Study}
\author{Frederick J. Boehm}
\author{Min-Lee Yang}
\author{Xiang Zhou}
\author{Santhi K. Ganesh}
\institution{University of Michigan}

\section{Introduction}
\textbf{Fibromuscular dysplasia (FMD)} is a systemic disease of artery walls that decreases target organ perfusion. 
Approximately 90\% of FMD cases are women. 
Investigators have identified \textbf{chronic kidney disease (CKD)} as a possible consequence.
% is there other evidence for this relationship? actual epidemiology studies??
% cite the actual case studies!!
\begin{center}
\includegraphics[width=\textwidth]{Fibromuscular.png}
\end{center}    

\begin{itemize} % perhaps add facts or evidence in itemized list below, to tie ckd to fmd
\item FMD often affects renal arteries \cite{olin2012united}.
\item FMD complications include stroke, dissection, \& aneurysm \cite{olin2012united}.
\end{itemize}

\section{Mendelian Randomization}


% https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41431-022-01038-5/MediaObjects/41431_2022_1038_Fig1_HTML.png?as=webp
    \includegraphics[width=\textwidth]{mr.png} % is this the figure that I want to use? 
    % Check the latest figures in teh Gen Epi letter about MR diagrams
    \cite{de2022understanding}


\section{CKD GWAS \cite{neale_lab_gwas}}
\begin{itemize}
\item 194,174 female UK Biobank subjects \cite{bycroft2018uk}
\end{itemize}



%% This fills the space between the content and the logo
\vfill

%% Institution logo
\includegraphics[width=\textwidth]{Michigan-Medicine_Logo-Horizontal-CMYK.png}\\

}{
%%%%%%%% RIGHT COLUMN


\section{FMD GWAS Meta-analysis \cite{georges2021genetic}}
\begin{itemize}
\item Six case-control studies from USA and Europe  
\item 1556 cases \& 7100 controls  
\item Tested 5.5 million SNPs  
\item Identified four risk loci for FMD: \textit{PHACTR1, LRP1, LIMA1, ATP2B1}  
\end{itemize}
\includegraphics[width=\textwidth]{georges2021-Fig1.png} 








\section{MR Results}

<<echo=FALSE>>=
myanalysisdir <- file.path("~/work", "notebook2", "fmdmr", "analysis")
mydir <- file.path(myanalysisdir, "data", "analysis_intermediates")
dat_harm <- readRDS(file.path(mydir, "fmd_ckd_dat_harm.rds")) |> tibble::as_tibble()
result <- TwoSampleMR::mr(dat_harm) 
result_het <- TwoSampleMR::mr_heterogeneity(dat = dat_harm)
result_pleiotropy <- TwoSampleMR::mr_pleiotropy_test(dat = dat_harm)
pp <- TwoSampleMR::mr_scatter_plot(mr_results = result, dat = dat_harm)
pp[[1]] + 
    ggplot2::xlim(- 0.5, 0.5) + 
    ggplot2::ylim(-0.001, 0.001) + 
    ggokabeito::scale_color_okabe_ito(name = "MR Test", alpha = .9)
fig_fn <- file.path(myanalysisdir, "results", "fmd_ckd_mr_scatter_plot.png")
ggplot2::ggsave(fig_fn)
@



\includegraphics[width=\textwidth]{\Sexpr{fig_fn}}


\section{Conclusion}

\begin{itemize}
\item No MR evidence that FMD causes CKD  
\item Larger FMD GWAS needed  
\end{itemize}



\section{Contact}
\textbf{Fred Boehm} frederick.boehm@gmail.com \url{https://fboehm.us}\\
\textbf{Funding}: \url{https://bit.ly/3UDwd2S}

\section{References}
\printbibliography[heading=none]



}
\end{document}
